# -*- coding: utf-8 -*-
"""08/02/24/Ejercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HHVGtlY6hyhZ7JTHm5D8PGqAH1EG2kX2
"""

Programa Que lea un numero e indica si es cero, positivo y negativo

x=int(input("Dame un numero: "))
if x == 0:
  print("Es cero")
elif x > 1:
  print("Es positivo")
else:
  print("Es negativo")

"""Menu v1:"""

print("Menu")
opc=0
while opc !=4:

  print('[1]Imprimir un nombre')
  print('[2]Pedir la suma de dos numeros')
  print('[3]Cacular el area de un triangulo' )
  print('[4]Salir')
  opc=(int(input("Ingrese una opcion")))


  if opc == 1:
    print("Has elegido la opcion 1: ")
    print("Tu nombre es: Joselyn ")

  elif opc == 2:
    print("Has elegido la opcion 2:")
    a=int(input("Dame un numero: "))
    b=int(input("Dame otro numero: "))
    c = a+b
    print("el resultado es: ", c)

  elif opc == 3:
    print("Has elegido la opcion 3:")
    base=int(input("Dame la base de tu triangulo: "))
    altura=int(input("Dame el area de tu triangulo: "))
    area = ((base*altura)/2)
    print("El area es: ", area)

  elif opc == 4:
    print("Saliendo")

"""Menu v2:"""

print("Menu")
opc=0
while opc !=4:
  print('[1]Imprimir un nombre')
  print('[2]Pedir la suma de dos numeros')
  print('[3]Cacular el area de un triangulo' )
  print('[4]Salir')
  opc=(int(input("Ingrese una opcion")))

match opc:
  case 1:
    print("Has elegido la opcion 1: ")
    print("Tu nombre es: Joselyn ")

  case 2:
    print("Has elegido la opcion 2:")
    a=int(input("Dame un numero: "))
    b=int(input("Dame otro numero: "))
    c = a+b
    print("el resultado es: ", c)

  case 3:
    print("Has elegido la opcion 3:")
    base=int(input("Dame la base de tu triangulo: "))
    altura=int(input("Dame el area de tu triangulo: "))
    area = ((base*altura)/2)
    print("El area es: ", area)

  case 4:
    print("Saliendo")

"""Menu v3:"""

def mostrar_menu(opciones):
  print('seleccione una opción: ')
  for clave in sorted(opciones):
    print(f' {clave}) {opciones[clave][0]}')

def leer_opcion(opciones):
  while(a := input('Opción: ')) not in opciones:
    print('Opción incorrecta, vuelva a intentarlo.')
  return a

def ejecutar_opcion(opcion, opciones):
  opciones[opcion][1]()

def generar_menu(opciones, opcion_salida):
  opcion = None
  while opcion != opcion_salida:
    mostrar_menu(opciones)
    opcion = leer_opcion(opciones)
    ejecutar_opcion(opcion, opciones)
    print()

def menu_principal():
  opciones = {
    '1': ('Imprimir un nombre', accion1),
    '2': ('Pedir la suma de dos numeros', accion2),
    '3': ('Cacular el area de un triangulo', accion3 ),
    '4': ('Salir', salir)
  }
  generar_menu(opciones, '4')

def accion1():
    print('Has elegido la opcion 1: ')
    print('Tu nombre es: Joselyn ')

def accion2():
    print("Has elegido la opcion 2:")
    a=int(input("Dame un numero: "))
    b=int(input("Dame otro numero: "))
    c = a+b
    print("el resultado es: ", c)

def accion3 ():
    print("Has elegido la opcion 3:")
    base=int(input("Dame la base de tu triangulo: "))
    altura=int(input("Dame el area de tu triangulo: "))
    area = ((base*altura)/2)
    print("El area es: ", area)

def salir():
    print("Saliendo")

if __name__== '__main__':
  menu_principal()